sudo: required
services:
  - docker

before_install:
  - docker build -t salemhusseini/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true salemhusseini/react-test npm test -- --coverage
#- docker run salemhusseini/react-test npm test -- --coverage

# after_success:
#   - docker build -t salemhusseini/multi-front ./front
#   - docker build -t salemhusseini/multi-nginx ./nginx
#   - docker build -t salemhusseini/multi-server ./server
#   - docker build -t salemhusseini/multi-worker ./worker
